source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SUCheckButton_Example', :exclusive => true do
  pod "SUCheckButton", :path => "../"
end

target 'SUCheckButton_Tests', :exclusive => true do
  pod "SUCheckButton", :path => "../"

  
end
